### ISSUE TITLE
cant open by https

### ISSUE THREAD

**Issue by cleverboy32** [kzahel/web-server-chrome#106] opened 2017-08-31 07:35 UTC
i ready do the add to homescreen , and found this need request by https. but i input the url : https://127.0.0.1:8887,it cannt conncetion.  said 404

**Comment by SimplyCodin** [comment] 2017-09-30 22:21
That's because the app dosen't support https

**Comment by kzahel** [comment] 2017-10-01 01:43
If you weren't on chromeos you could use something like https://ngrok.com/ or localtunnel.
I could build something into the app but probably it would require some kind of sign in

**Comment by kzahel** [comment] 2017-11-08 18:43
Duplicate of https://github.com/kzahel/web-server-chrome/issues/113

**Closed by kzahel** 2017-11-08 18:43 UTC
