### ISSUE TITLE
Access html without file extension

### ISSUE THREAD

**Issue by tockiib** [kzahel/web-server-chrome#188] opened 2019-09-06 13:58 UTC
I am using this chrome extension for making my Github page.
In Github page, if you access to xxx.x/asdf, it connects to xxx.x/asdf.html but this extension won't do it and say "entry not found".
Is there any option for this feature?

**Comment by ecc521** [comment] 2019-10-12 22:00
This issue is a duplicate of #186.

**Closed** 2019-10-14 01:25 UTC
