### ISSUE TITLE
Add support for SPA using HTML5 history

### ISSUE THREAD

**Issue by thevukaslt** [kzahel/web-server-chrome#89] opened 2017-01-21 17:16 UTC
Hey,
I think it's crucial nowadays to have support for SPA that are using modern html5 history for routing.

In other words we need option to fallback on index.html in case actual folder/file is not found in directory.

**Comment by kzahel** [comment] 2017-01-21 17:24
Isn't that already an option ? Don't you see in in the app settings?

**Comment by thevukaslt** [comment] 2017-01-21 17:26
Hmm... Sorry, but I can't see such

**Comment by thevukaslt** [comment] 2017-01-21 17:58
If you mean "automatically show index.html", it's probably broken in the way I meant.

It only works in root, requesting address IP:PORT/dynamic/url, however, will result in error 404 and "entry not found" text line displayed.

**Comment by kzahel** [comment] 2017-01-21 21:29
That sounds like a bug. If you add / at the end of your URL does it work?
Maybe you have a symlink?

**Comment by thevukaslt** [comment] 2017-01-22 07:20
No, trailing slash does nothing. Still get "entry not found" line and 404. Tried on both chrome dev and canary, both latest as of writing time.

Hopefully there is an easy fix for this.

SYS Info:
• Win10,
• Chrome Version 57.0.2986.0 (Official Build) dev (64-bit) and Version 58.0.2988.0 (Official Build) canary (64-bit). (Canary has no extensions).

**Comment by kzahel** [comment] 2017-01-22 09:19
Is your index html file all lower case ? Does it work if you go to the full
URL?

**Comment by thevukaslt** [comment] 2017-01-22 09:20
Yes, all lower case. What do you mean by full URL?

**Comment by thevukaslt** [comment] 2017-02-07 13:24
What's state is it?

**Comment by thevukaslt** [comment] 2017-02-16 17:19
To clear even further (should have mention this earlier, sorry) as [cgriffin4](https://github.com/kzahel/web-server-chrome/issues/86#issuecomment-280393303) noted is exact problem I tried explain here. 

In my app which specifically is built with AngularJS uses moderm HTML5 URL rewriting:
`$locationProvider.html5Mode(true);`
so my URL appears pretty without any hashtags. 

Basically it's the same issue as in [#86](https://github.com/kzahel/web-server-chrome/issues/86#issuecomment-280393303), so, feel free to merge them. :)

**Comment by kzahel** [comment] 2017-02-16 17:25
Duplicate of https://github.com/kzahel/web-server-chrome/issues/86

**Closed by kzahel** 2017-02-16 17:25 UTC
